<?php

/* what type of experiment is this? */
$stim_type = 'audio1';
$resp_type = '2AFC_labels';

/* The name of the file where trial-by-trial data are stored. */
$datafile = 'ACat_Data.csv';

/* The name of the file where subject questionnaire data are stared */
$subjects = 'ACat_Subj.csv';

/* stimulus list name template - will replace ## with a list number */
$template = "js/ACat_list##.js";
?>
