<?php

/* what type of experiment is this? */
$stim_type = 'audio1';
$resp_type = 'text';

/* The name of the file where trial-by-trial data are stored. */
$datafile = 'ATrans_Data.csv';

/* The name of the file where subject questionnaire data are stared */
$subjects = 'ATrans_Subj.csv';

/* stimulus list name template - will replace ## with a list number */
$template = "js/ATrans_list##.js";
?>
