<?php

/* what type of experiment is this? */
$stim_type = 'text';
$resp_type = 'recording';

/* The name of the file where trial-by-trial data are stored. */
$datafile = 'RecList_Data.csv';

/* The name of the file where subject questionnaire data are stared */
$subjects = 'RecList_Subj.csv';

/* stimulus list name template - will replace ## with a list number */
$template = "js/RecList_list##.js";

$recordings_directory = "audio_recordings/";
?>
