<?php

/* what type of experiment is this? */
$stim_type = 'video';
$resp_type = '2AFC_labels';

/* The name of the file where trial-by-trial data are stored. */
$datafile = 'VCat_Data.csv';

/* The name of the file where subject questionnaire data are stared */
$subjects = 'VCat_Subj.csv';

/* stimulus list name template - will replace ## with a list number */
$template = "js/VCat_list##.js";
?>
