#! /usr/bin/perl
use File::Basename;

$csvname = $ARGV[0];

open $in, '<:encoding(UTF-8)',$csvname or die $1;

$final_silence = 0.2;  
$sf = 16000;
$target_width = 512;

# make a final silent interval, so movie playback doesn't truncate stimulus audio
$info = system("sox -n -r $sf -c 1 temp/final_silence.wav trim 0.0 $final_silence");

while ($line = <$in>) {

    ($outfile,$imagefile, $imagedur, $soundfile, $snd_offset, $response_picture) = split(/,/,$line);
    print("make $outfile from $soundfile and $imagefile\n"); 

    # condition soundfile (set sampling rate, 1 channel, amplitude normalize)
    $info = system("sox \"$soundfile\" temp/temp.wav channels 1 rate $sf norm -3");

    # make a silent interval -- no input (-n)
    $info = system("sox -n -r $sf -c 1 temp/silence.wav trim 0.0 $snd_offset");
    
    # add silence to front of sound to produce sound track of AV stimulus
    $info = system("sox temp/silence.wav temp/temp.wav temp/final_silence.wav temp/soundtrack.wav");

    # construct the concat input text file
    open $fh, '>', "picture_input.txt" or die "Can't open picture_input.txt for writing: $!";
    print $fh "file $imagefile\n";
    print $fh "duration $imagedur\n";
    print $fh "file $response_picture\n";
    close $fh;

    # concat pictures with duration specifications in "picture_input.txt" and add soundtrack
    $info = system("ffmpeg -f concat -i picture_input.txt -i temp/soundtrack.wav ".
                   "-c:v libx264 -vsync vfr -pix_fmt yuv420p ".
		   "-c:a aac -max_interleave_delta 100M -y \"$outfile\" ");
}
